env:
  - GHCVER=7.8.3 ESVER=1.4.1
before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install cabal-install-1.20 ghc-$GHCVER
  - sudo apt-get install happy-1.19.3
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/happy/1.19.3/bin:$PATH

install:
  - cabal-1.20 update
  - cabal-1.20 install --only-dependencies --enable-tests --force-reinstalls

script:
  - cabal-1.20 configure --enable-tests -v2
  - cabal-1.20 build
  - cabal-1.20 test
  - cabal-1.20 check
  - cabal-1.20 sdist
